# Generated by Django 4.2.5 on 2023-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинофильм', 'verbose_name_plural': 'Кинофильмы'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка видео'),
        ),
    ]
